### ISSUE TITLE
Core review

### ISSUE THREAD

**Issue by Dan86de** [SzymonRojek/single-price-grid-component#1]
Tutaj wszystko co bym zmienił :)

**Comment by Dan86de** [comment]
Wszystkie pytania masz poniżej 

plik main.css

- linia 42 i 43 nic nie wnoszą chyba można to usunąć?
 `  background-color: #f2f2f2;
  z-index: 3;`
- zagnieżdżanie klas jest dobre jak chcesz się upewnić, że nie namieszasz nic i klasy nie będą na siebie oddziaływać zbytnio ale u Ciebie w projekcie to chyba jest nadużywane 
`.wrapper-component .main-component .card-2__pricing-price`
Chyba użyłbym po prostu card-2 i dalej następnych. To kwestia do dogadania w projekcie.
- h1.heading-primary ma za duży padding na górze przez co nie wygląda jak na designie

Póki co to tyle znalazłem reszta jak na ten etap wydaje się spoko :)
 👍

**Comment by SzymonRojek** [comment]
*Cześć Danielu, *

Pięknie dziękuje!

   - Faktycznie background-color usunąłem, ale z-index musi zostać, gdyż
   box-shadow jest na tym indexie i bez tego widać linię górną footera;
   - Zależy o których zagnieżdżonych piszesz, czy tych w main.css? bo tam
   te powtórzenia powstają w wyniku sassowych zapisów, dlatego pytałem czy w
   sassie dobrze zrobiłem całość jako jeden rulset, czy po prostu
   porozdzielać to wszystko na małe fragmenty;
   - h1 padding zmniejszony - DOBRE OKO masz :)
   - ps. dodałem jeszcze opacity na tekst w karcie trzeciej, bo faktycznie
   na design on jest;

Serdecznie Cię pozdrawiam

wt., 22 gru 2020 o 04:57 Daniel Noworyta <notifications@github.com>
napisał(a):
